# Generated by Django 2.0.9 on 2019-01-13 21:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(blank=True, choices=[('P', 'Partner'), ('C', 'Customer')], max_length=50)),
                ('brief', tinymce.models.HTMLField(blank=True, db_index=True, max_length=500)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(blank=True, choices=[('P', 'Product'), ('L', 'Solution'), ('S', 'Service'), ('V', 'Vacancy'), ('N', 'News'), ('J', 'Project'), ('A', 'About')], max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('brief', tinymce.models.HTMLField(blank=True, db_index=True, max_length=500)),
                ('description', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000)),
                ('characteristic', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000)),
                ('resources', tinymce.models.HTMLField(blank=True, db_index=True, max_length=2000)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(blank=True, choices=[('I', 'Image'), ('V', 'Video'), ('D', 'Doc')], max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('data', models.ImageField(upload_to=models.CharField(blank=True, choices=[('I', 'Image'), ('V', 'Video'), ('D', 'Doc')], max_length=50))),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.Upload'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.Upload'),
        ),
    ]
